export const config = {
  ENDPOINT_BACKEND: process.env.REACT_APP_ENDPOINT_BACKEND,
  ENDPOINT_QUOTA: process.env.REACT_APP_ENDPOINT_QUOTA,
  ENDPOINT_NEGOTIATION: process.env.REACT_APP_ENDPOINT_NEGOTIATION,
  ENDPOINT_CHAT: process.env.REACT_APP_ENDPOINT_CHAT,
  ENDPOINT_SEARCH_CEP: process.env.REACT_APP_ENDPOINT_SEARCH_CEP,
  ENDPOINT_SALE: process.env.REACT_APP_ENDPOINT_SALE,
  ENDPOINT_NOTIFICATION: process.env.REACT_APP_ENDPOINT_NOTIFICATION,
  ENDPOINT_ADMINISTRATOR: process.env.REACT_APP_ENDPOINT_ADMINISTRATOR,
  ENDPOINT_SIMULATOR: process.env.REACT_APP_ENDPOINT_SIMULATOR,
  ENDPOINT_UPLOADER: process.env.REACT_APP_ENDPOINT_UPLOADER,
  ENDPOINT_ZAMMAD: process.env.REACT_APP_ENDPOINT_ZAMMAD,
};
