export default {
  HANDLEPROFESSIONALS: 'HANDLE_PROFESSIONALS',
  HANDLELOADINGPROFESSIONALS: 'HANDLE_LOADING_PROFESSIONALS',
  HANDLEMODALPROFESSIONALS: 'HANDLE_MODAL_PROFESSIONALS',
  HANDLEFILTERS: 'HANDLEFILTERS',
};
