export default {
  SETREQUESTS: 'SET_REQUESTS',
  SETSELECTEDREQUEST: 'SET_SELECTED_REQUEST',
  SETINTERVIEWDATE: 'SET_INTERVIEW_DATE',
  HANDLELOADINGREQUESTS: 'HANDLE_LOADING_REQUESTS',
  HANDLEMODALREQUESTS: 'HANDLE_MODAL_REQUESTS',
};
